baseurl: https://goethe-erc-team.netlify.app
DefaultContentLanguage: en
title: Goethe University - ERC Team
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: yes
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon.ico
  logo: img/logo-cookie.jpeg
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: yes
  showRelatedPosts: yes
  socialShare: yes
  subtitle: Economic Consequences of Restrictions on the Usage of Cookies
  useHLJS: yes
  wordCount: no
Author:
  # 500px: username
  # bandcamp: username
  # bitbucket: username
  # codepen: username
  email: goethe-university-erc-team@protonmail.com
  # facebook: username
  github: username
  # gitlab: username
  # instagram: username
  # itchio: username
  # kaggle: username
  # linkedin: username
  # mastodon: url
  name: ERC Advanced Investigator Grant
  # paypal: username
  # reddit: username
  # slack: username
  # snapchat: username
  # soundcloud: username
  # spotify: username
  # stackoverflow: users/XXXXXXX/username
  # telegram: username
  # twitter: username
  # vk: username
  website: yourwebsite.com
  # weibo: username
  # xing: username
  # youtube: user/username
menu:
  main:
  # 1st tab
    - identifier: research
      name: Research
      url: ''
      weight: 1
  # 1st sub-tab of tab 1
    - name: ERC Grant
      parent: research
      url: page/erc-grant
      weight: 1
  # 2nd sub-tab of tab 1
    - name: Projects
      parent: research
      url: page/research-projects
      weight: 2
  # 3rd sub-tab of tab 1
    - name: Upcoming Talks
      parent: research
      url: page/upcoming-talks
      weight: 3
  # 4th sub-tab of tab 1
    - name: Past Talks
      parent: research
      url: page/past-talks
      weight: 4
  # 2nd tab
    - name: Team
      url: page/team
      weight: 2
  # 3rd tab
    - name: Blog
      url: ''
      weight: 5
    # - name: Blog
    #   url: ''
    #   weight: 1
    # - name: About Us
    #   url: page/about/
    #   weight: 3
    # - identifier: samples
    #   name: Samples
    #   weight: 2
    # - name: Big Image Sample
    #   parent: samples
    #   url: post/2017-03-07-bigimg-sample
    #   weight: 1
    # - name: Math Sample
    #   parent: samples
    #   url: post/2017-03-05-math-sample
    #   weight: 2
    # - name: Code Sample
    #   parent: samples
    #   url: post/2016-03-08-code-sample
    #   weight: 3
    # - name: Tags
    #   url: tags
    #   weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
