baseurl: https://goethe-erc-team.netlify.app
DefaultContentLanguage: en
title: Goethe University - ERC Team
theme: beautifulhugo
metaDataFormat: yaml
pygmentsStyle: trac
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
Params:
  comments: no
  commit: no
  dateFormat: January 2, 2006
  delayDisqus: yes
  favicon: img/favicon-cookie.ico
  logo: img/logo-cookie.jpeg
  mainSections:
    - post
    - posts
  readingTime: yes
  rss: no
  showRelatedPosts: yes
  socialShare: yes
  subtitle: Economic Consequences of Restrictions on the Usage of Cookies
  useHLJS: yes
  wordCount: no
Author:
  name: ERC Advanced Investigator Grant
  email: goethe-university-erc-team@protonmail.com
  github: https://github.com/goethe-university-erc-team
  website: https://goethe-erc-team.netlify.app
  # 500px: username
  # bandcamp: username
  # bitbucket: username
  # codepen: username
  # facebook: username
  # gitlab: username
  # instagram: username
  # itchio: username
  # kaggle: username
  # linkedin: username
  # mastodon: url
  # paypal: username
  # reddit: username
  # slack: username
  # snapchat: username
  # soundcloud: username
  # spotify: username
  # stackoverflow: users/XXXXXXX/username
  # telegram: username
  # twitter: username
  # vk: username
  # weibo: username
  # xing: username
  # youtube: user/username
menu:
  main:
  # 1st tab
    - identifier: research
      name: Research
      url: ''
      weight: 1
  # 1st sub-tab of tab 1
    - name: ERC Grant
      parent: research
      url: page/erc-grant
      weight: 1
  # 2nd sub-tab of tab 1
    - name: Projects
      parent: research
      url: page/research-projects
      weight: 2
  # 3rd sub-tab of tab 1
    - name: Upcoming Talks
      parent: research
      url: page/upcoming-talks
      weight: 3
  # 4th sub-tab of tab 1
    - name: Past Talks
      parent: research
      url: page/past-talks
      weight: 4
  # 2nd tab
    - name: Team
      url: page/team
      weight: 2
  # 3rd tab
    - name: Blog
      url: ''
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true
