---
title: ""
---

# Books

Skiera, Bernd / Miller, Klaus / Jin, Yuxi / Kraft, Lennart / Laub, René / Schmitt, Julia (2022), [*"The Impact of the General Data Protection Regulation (GDPR) on the Online Advertising Industry"*](https://leanpub.com/gdpr-impact%20and%20www.gdpr-impact.com)

# Articles in Academic Journals

Jin, Yuxi / Skiera, Bernd, ["How do Privacy Laws Impact the Value for Actors in the Online Advertising Market?---A comparison of the EU, US, and China"](https://doi.org/10.1177/23949643221117676), *Journal of Creating Value, forthcoming*.

# Conference Proceedings

Kraft, Lennart / Miller, Klaus / Skiera, Bernd (2021), "Density, Pace, and Consistency in Third-Party Consumer Profiling", *Proceedings of EMAC 2021 - The 50th Annual Conference of the European Marketing Academy*.

Laub, René / Miller, Klaus / Skiera, Bernd (2021), "The Economic Value of Online User-Tracking", *Proceedings of EMAC 2021 - The 50th Annual Conference of the European Marketing Academy*.

# Working Papers

Miller, Klaus / Skiera, Bernd (2022), *"Economic Consequences of Online Tracking Restrictions"*, Working Paper, under revision for second-round review at International Journal of Research in Marketing.

Schmitt, Julia / Miller, Klaus / Skiera, Bernd, *"The Impact of Privacy Laws on Online User Behavior"*, Working Paper, under revision for third-round review at Journal of Marketing Research.

Schmitt, Julia, *"Choose Wisely: The Impact of Consent Banner Designs on Consent Rates"*, Working Paper.

Schmitt, Julia, *"The Illusion of Control: Control and Convenience on Consent Banners"*, Working Paper.

Laub, René / Miller, Klaus / Skiera, Bernd, *"The Economic Value of User-Tracking for Publishers"*, Working Paper.

Laub, René / Kraft, Lennart, *"Impact of Amount of Traffic and Number of Advertisers on Publisher Revenue in Real-Time-Bidding"*, Working Paper.

Lukic, Karlo / Miller, Klaus / Skiera, Bernd, *"The Impact of the General Data Protection Regulation (GDPR) on Online Tracking"*, Working Paper.

Kraft, Lennart / Miller, Klaus / Skiera, Bernd, *"Richness and Consistency of Consumer Profiles and Their Development over Time"*, Working Paper.

Kraft, Lennart, *"Leveraging Differential Privacy for Targeted Advertisements"*, Working Paper.

Kraft, Lennart, *"Tax Revenue, Privacy, and Profits under Taxed Targeted Advertisements"*, under revision for second-round review at International Journal of Research in Marketing.

Kraft, Lennart / Skiera, Bernd, *"Economic Impact of Apple's App Tracking Transparency (ATT)"*, Working Paper.

Kraft, Lennart / Skiera, Bernd, *"Usage of Legal Bases under GDPR"*. Working Paper.

Jin, Yuxi / Skiera, Bernd, *"How Does a Standard to Implement Privacy Regulations Affect Web Traffic and Tracking? Evidence from IAB's Transparency and Consent"*, Working Paper.

# Dissertations

Kraft, Lennart, *"Price of Privacy"*, defended on July 18, 2022.

Schmitt, Julia, *"The Impact of Privacy Laws on Websites and Users"*, defended on December 20, 2021.

# Master Theses

Klimmesch, Pascal (2022), *"A Bright Future After Third-Party Cookies? Evaluating New Solutions for Digital Advertising from an Economic and Privacy Perspective"*, Supervised by Timo Mueller-Tribbensee, Bernd Skiera.

# Bachelor Theses

Grimmer, Ann-Kathrin (2022) *"The Renaissance of Contextual Targeting"*, Supervised by Timo Mueller-Tribbensee, Bernd Skiera.

Botzke, Robin (2022) *"Die Kosten einer werbefreien digitalen Welt" ("The Cost of an Ad-Free Digital World")*, Supervised by Timo Mueller-Tribbensee, Bernd Skiera.

Stadnik, Maximilian (2021) *"Vergleich länderspezifischer Interpretationen europäischer Datenschutzgesetze" ("Comparison of Country-Specific Interpretations of European Privacy Laws")*, Supervised by Julia Schmitt, Bernd Skiera.

Santoso, Jarod (2021) *"Eine Untersuchung der Nutzerreaktionen zu werbe- und trackingfreien Abonnements digitaler Zeitungen" ("Identifying User Reactions to Advertising- and Tracking-Free Digital Newspaper Subscriptions")*, Supervised by Timo Mueller-Tribbensee, Bernd Skiera.

Rahimi, Mariam (2021) *"A Comparison of Existing Privacy Laws Worldwide"*, Supervised by Julia Schmitt, Bernd Skiera.

Brand, Sophia (2021) *"The Role of Consumer Privacy for the Personalization of Marketing Instruments"*, Supervised by René Laub, Bernd Skiera.

Linke, Roland (2021) *"Exploring the Privacy Paradox in the Smartphone App Market*", Supervised by René Laub, Bernd Skiera.

Röder, Daniel (2021), *"The Relevance of User-Tracking for the Provision of Free Online-News: An Empirical Analysis"*, Supervised by René Laub, Bernd Skiera.

Rubrecht, Leon (2022), *"How Privacy-Intrusive are Smartphone Apps?"*, Supervised by René Laub, Bernd Skiera.

Hilpert, Phillip (2021), *"Why Do Consumer Use Ad-blockers? No Ads or More Privacy?"*, Supervised by Yuxi Jin, Bernd Skiera.

Gaydarzhy, Margaryta (2021), *"Do Cheaper Mobile Apps Require More Privacy Sensitive Permissions?"*, Supervised by Yuxi Jin, Bernd Skiera.

Brueggemann, Merle (2021), *"Are Online Users in Europe tracked less than Online Users in the US?"*, Supervised by Yuxi Jin, Bernd Skiera.

Herz, Katarina(2021), *"Do Larger Websites Offer More Privacy?"*, Supervised by Yuxi Jin, Bernd Skiera

Bilge, Ebru (2020),*"Ein Überblick über die Veränderung der rechtlichen Situation in ausgewählten EU-Ländern nach Einführung der DSGVO" ("An Overview of the Change in the Legal Situation in Selected EU-Countries After the Enforcement of the GDPR")*, Supervised by Julia Schmitt, Bernd Skiera.

Karadoruk, Ali (2020),*"Die Verwendung von Cookies im Internet" ("The Usage of Cookies on the Internet")*, Supervised by Julia Schmitt, Bernd Skiera.

Hohmann, Annika (2019), *"Using the Privacy Calculus to Improve Data Collection"*, Supervised by Julia Schmitt, Bernd Skiera.

Damci, Yeliz (2018), *"Das Privacy Paradox: Eine Analyse des Forschungsstandes und der Reduktionsmöglichkeiten" ("The Privacy Paradox: An Analysis of the State of Research and Reduction Possibilities")*, Supervised by Julia Schmitt, Bernd Skiera.

Mahdi, Elias Ahmedahir (2021), *"Can Trackers on European Banking Websites be Justified in a Post-GDPR World"*, Supervised by Karlo Lukic, Bernd Skiera.

Wissel, Moritz (2021), *"Dark Patterns on German Websites in the Post-GDPR Period"*, Supervised by Karlo Lukic, Bernd Skiera.

Woodhoo, Vishaant (2022), *"Are Chrome Browser Extensions Less Risky After Google Updates?"*, Supervised by Karlo Lukic, Bernd Skiera.

Kaffee, Jonas (2022), *"Exploring the Market of Chrome Browser Extensions"*, Supervised by Karlo Lukic, Bernd Skiera.

Walter, Marcel (2022), *"Tracking Your Food Delivery: Trackers in Food Delivery Apps"*, Supervised by Karlo Lukic, Bernd Skiera.
