---
title: "Workshops"
toc: false
---

## Organization of Workshops and Invitations to Seminar Series

2023-05: EMAC: Privacy Sessions

2023-03-19: Participation as Evaluator for Habilitation of Julien
Cloarec (Université Toulouse Capitole, France) on \"Privacy in the Age
of Artificial Intelligence: Insights from a Multi-Stream Research
Program\"

2022-11-14: Online Presentation of Vincent Lefrere (Institut
Mines-Télécom, Business School, LITEM) on \"Usage of OpenWPM\"

2022-10-25: Presentation of Vincent Lefrere (Institut Mines-Télécom,
Business School, LITEM) on \"Privacy, Data and Competition: The Case
of Apps For Young Children\", Goethe University Frankfurt

2022-09-23: Visit of Professor Nico Neumann from Melbourne Business
School (Australia), Presentation: "Friend or Foe? Social Media
Privacy, and The Sharing of News"

2022-06-16: Klaus Miller & Bernd Skiera, Special Sessions on "Online
Consumer Privacy" at INFORMS Marketing Science Conference (virtual
meeting).

2022-05-25 and 2022-05-27; Klaus Miller & Bernd Skiera, Special
Session "Online Consumer Privacy" at EMAC 2022 (Session 1 on May 25,
Session 2 on May 27)- The 51th Annual Conference of the European
Marketing Academy, Budapest, Hungary.

2021-06-30: Martin Risius (University of Queensland, Brisbane,
Australia), "Developing a New Paradigm to Solve the Privacy Paradox"
(virtual seminar series)f

2021-06-23: Sam Macbeth (software developer at
DuckDuckGo/Cliqz/Ghostery and PhD graduate from Imperial College
London, UK), "DuckDuckGo Workshop" (joint virtual workshop with
TechAcademy Frankfurt)

2021-05-26: Klaus Miller & Bernd Skiera, Special Session "Online
Consumer Privacy" at EMAC 2021 - The 50th Annual Conference of the
European Marketing Academy

2020-03-18: Organization of Special Session on "Consumer Privacy on
the Internet" at Yearly Conference of German Academic Association for
Business Research ("Verband der Hochschullehrer für Betriebswirtschaft
e.V. (VHB)")
